### ISSUE TITLE
User list overlap issue on multi-user systems

### ISSUE THREAD

**Issue by b-simjoo** [birbkeks/win7-sddm-theme#5]
Hi,
Thanks for the great theme!

I encountered a UI issue when using the theme on a system with multiple users. When I select a user to log in (which triggers the password field to appear), the other users are still visible in the background or beneath the selected user, causing visual overlap.

Even after entering the password, when the “Welcome” message appears, the user list remains visible behind it.

Steps to reproduce:

    Have multiple user accounts (e.g., 3 or more).

    Boot into SDDM with this theme.

    Click on one user to log in.

    Notice that other users are still visible under or around the selected user and password field.

    Enter the password – observe that the “Welcome” message appears, but the user list is still visible in the background.

System info:

    OS: KDE Neon 6.3

    SDDM version: 0.21.0

Let me know if you need a screenshot or video of the issue — I’d be happy to provide one!

**Comment by syrupderg** [comment]
can you send a photo/video of the problem?

**Comment by syrupderg** [comment]
i already fixed this problem with [this commit](https://github.com/birbkeks/win7-sddm-theme/commit/ff13e68dd71d315d27b5784feb67cc00dd736d94), are you using the newest version?

**Comment by b-simjoo** [comment]
I recently fully reinstalled and issue still exists.

![Image](https://github.com/user-attachments/assets/4bcb92a4-c39e-4f63-a201-f92815927002)

**Comment by b-simjoo** [comment]
I found this code in theme directory that shows I installed and older version.

```
Image {
    width: 99
    height: 15

    source: "../Assets/caps.png"

    smooth: false
}
```

Please check KDE store, seems it is outdated

**Comment by b-simjoo** [comment]
Also the `.tar` file in github release seems old. It has the same lines that I mentioned

**Comment by b-simjoo** [comment]
You may want to close this issue after updated releases on GitHub and KDE store.

**Comment by syrupderg** [comment]
> Also the `.tar` file in github release seems old. It has the same lines that I mentioned

oh no, i totally forgot to update the release files, ill look into it asap

**Comment by syrupderg** [comment]
i updated all the releases and it should be now fixed
